### ISSUE TITLE
Imperial units are completely incorrect

### ISSUE THREAD

**Issue by Kyosant** [iseau395/vrc-map#17]
Basically, when you go to the top and select "Imperial Units" all the measurements are a little under twice as long. Upon investigation, it seems metric is off too.

**To Reproduce**
1. click at one border of the tile
2. click the other
3. measurements are wrong

**Expected behavior**
For the units to be correct

**Screenshots**
![image](https://user-images.githubusercontent.com/103342644/162597192-551afb5b-a997-480e-8ad9-be230a320313.png)

this should be  24in, not 46

**Desktop **
 - Win 11
 - Opera GX

**Comment by iseau395** [comment]
Thanks for pointing this out! I forgot to scale down the distances when I made the map size bigger a bit ago.
